# Generated by Django 5.2.1 on 2025-05-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Question Name'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
