# Generated by Django 5.2.1 on 2025-05-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_question_text_delete_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='classrooms',
            fields=[
                ('classroom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=10)),
                ('building', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course_schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.classrooms')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.departments'),
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('faculty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('hire_date', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.departments')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.faculty'),
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.departments')),
            ],
        ),
        migrations.CreateModel(
            name='enrollments',
            fields=[
                ('enrollment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('grade', models.CharField(max_length=2)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.courses')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.students')),
            ],
        ),
    ]
