# Generated by Django 5.2.1 on 2025-05-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_classrooms_courses_departments_course_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_schedule',
            name='classroom_id',
        ),
        migrations.RemoveField(
            model_name='course_schedule',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='faculty_id',
        ),
        migrations.RemoveField(
            model_name='enrollments',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='enrollments',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='classrooms',
        ),
        migrations.DeleteModel(
            name='course_schedule',
        ),
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.DeleteModel(
            name='faculty',
        ),
        migrations.DeleteModel(
            name='departments',
        ),
        migrations.DeleteModel(
            name='enrollments',
        ),
        migrations.DeleteModel(
            name='students',
        ),
    ]
