# Generated by Django 5.2.1 on 2025-05-19 19:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_student_is_active_alter_student_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('critical', 'critical')], max_length=10)),
                ('messege_alert', models.TextField()),
                ('created_at', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('incoming_traffic_mb', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu_usage_percent', models.FloatField()),
                ('ram_usage_percent', models.FloatField()),
                ('disk_usage_percent', models.FloatField()),
                ('app_usage_percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_server', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='resourceusage',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.server'),
        ),
        migrations.AddField(
            model_name='networktraffic',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.server'),
        ),
        migrations.AddField(
            model_name='alert',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.server'),
        ),
    ]
