# Generated by Django 5.2.1 on 2025-05-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_server_id_alert_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name_of_server',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
